DROP TABLE TBL_FEED;

CREATE TABLE TBL_FEED(
    FEED_PNO NUMBER(10) PRIMARY KEY,
    FEED_CONTENT VARCHAR2(1000),
    FEED_USER_FNO NUMBER(10),
    FEED_DATE DATE DEFAULT SYSDATE,
    FEED_FILE VARCHAR2(300),
    FEED_ALT VARCHAR2(200)
);

DROP SEQUENCE SEQ_FEED;

CREATE SEQUENCE SEQ_FEED START WITH 1 INCREMENT BY 1;