DROP TABLE TBL_USER CASCADE CONSTRAINTS ;



CREATE TABLE TBL_USER (
	USER_PNO NUMBER(10) PRIMARY KEY,
	USER_EMAIL VARCHAR(200) UNIQUE NOT NULL,
	USER_PW VARCHAR(20) NOT NULL,
	USER_NICK VARCHAR(30) UNIQUE NOT NULL
);

DROP SEQUENCE SEQ_USER;

CREATE SEQUENCE SEQ_USER
	INCREMENT BY 1
	START WITH 1;

INSERT INTO TBL_USER VALUES (SEQ_USER.nextval, 'TEST@TEST.COM', '1234', 'TEST NICKK');

COMMIT
	
