DROP TABLE TBL_WIKI CASCADE CONSTRAINTS;

CREATE TABLE TBL_WIKI(
    WIKI_PNO NUMBER(10) PRIMARY KEY ,
    WIKI_USER_FNO NUMBER(10) NOT NULL,
    WIKI_CONTENT VARCHAR(2000) NOT NULL,
    WIKI_LANG VARCHAR2(20) NOT NULL,
    WIKI_COM_DATE DATE DEFAULT SYSDATE
);

DROP SEQUENCE SEQ_WIKI;

CREATE SEQUENCE SEQ_WIKI START WITH 1 INCREMENT BY 1;

