DROP TABLE TBL_REPLY;

CREATE TABLE TBL_REPLY(
    REPLY_PNO NUMBER(10) PRIMARY KEY,
    REPLY_USER_FNO NUMBER(10) NOT NULL,
    REPLY_DATE DATE DEFAULT SYSDATE,
    REPLY_FEED_FNO NUMBER(10) NOT NULL,
    REPLY_CONTENT VARCHAR2(255) NOT NULL,

    CONSTRAINT REPLY_USER_FNO FOREIGN KEY (REPLY_USER_FNO) REFERENCES  TBL_USER(USER_PNO) ON DELETE CASCADE,
    CONSTRAINT REPLY_FEED_FNO FOREIGN KEY (REPLY_FEED_FNO) REFERENCES TBL_FEED(FEED_PNO) ON DELETE CASCADE
);

DROP SEQUENCE SEQ_REPLY;

CREATE SEQUENCE SEQ_REPLY INCREMENT BY 1 START WITH 1;

INSERT INTO TBL_REPLY (REPLY_PNO, REPLY_USER_FNO, REPLY_FEED_FNO, REPLY_CONTENT)  VALUES (SEQ_REPLY.nextval, 1, 1, 'TEST REPLY');

COMMIT