DROP TABLE TBL_FOLLOW;

CREATE TABLE TBL_FOLLOW(
    FOLLOW_USER_FNO NUMBER(10) NOT NULL,
    FOLLOW_FOLLOWING_FNO NUMBER(10) NOT NULL,

    CONSTRAINT FOLLOW_USER_FNO FOREIGN KEY (FOLLOW_USER_FNO) REFERENCES  TBL_USER(USER_PNO) ON DELETE  CASCADE ,
    CONSTRAINT FOLLOW_FOLLOWING_FNO FOREIGN KEY (FOLLOW_FOLLOWING_FNO) REFERENCES TBL_USER(USER_PNO) ON DELETE CASCADE
);
