DROP TABLE TBL_FILES;

CREATE TABLE TBL_FILES(
    FILES_FEED_FNO NUMBER(10),
    FILES_FILE VARCHAR2(200),

    CONSTRAINT FILES_FEED_FNO FOREIGN KEY (FILES_FEED_FNO) REFERENCES TBL_FEED(FEED_PNO) ON DELETE CASCADE
);

INSERT INTO TBL_FILES VALUES (SEQ_FEED.currval, 'TEST FILE');
INSERT INTO TBL_FILES VALUES (SEQ_FEED.currval, 'TEST FILE');
INSERT INTO TBL_FILES VALUES (SEQ_FEED.currval, 'TEST FILE');

COMMIT;

SELECT * FROM TBL_FILES;