DROP TABLE TBL_HASHTAG;

CREATE TABLE TBL_HASHTAG(
    HASHTAG_FEED_FNO NUMBER(10) NOT NULL ,
    HASHTAG_CONTENT VARCHAR2(200) NOT NULL,

    CONSTRAINT HASHTAG_FEED_FNO FOREIGN KEY (HASHTAG_FEED_FNO) REFERENCES TBL_FEED(FEED_PNO) ON DELETE CASCADE
);

INSERT INTO TBL_HASHTAG VALUES (1, 'HI');

COMMIT