DROP TABLE TBL_FEED CASCADE CONSTRAINTS ;

CREATE TABLE TBL_FEED(
    FEED_PNO NUMBER(10) PRIMARY KEY,
    FEED_CONTENT VARCHAR2(1000) NOT NULL ,
    FEED_USER_FNO NUMBER(10) NOT NULL ,
    FEED_FILE VARCHAR2(200),
    FEED_DATE DATE DEFAULT SYSDATE,

    CONSTRAINT FEED_USER_FNO FOREIGN KEY (FEED_USER_FNO) REFERENCES TBL_USER(USER_PNO) ON DELETE CASCADE
);

DROP SEQUENCE SEQ_FEED;

CREATE SEQUENCE SEQ_FEED START WITH 1 INCREMENT BY 1;

INSERT INTO TBL_FEED(FEED_PNO, FEED_CONTENT, FEED_USER_FNO, FEED_FILE) VALUES (SEQ_FEED.NEXTVAL, 'TEST', 1, 'TESTFILE');

COMMIT ;
