DROP TABLE TBL_POFOL;

CREATE TABLE TBL_POFOL(
    POFOL_USER_FNO NUMBER(10) NOT NULL,
    POFOL_CONTENT VARCHAR2(200) NOT NULL,

    CONSTRAINT POFOL_USER_FNO FOREIGN KEY (POFOL_USER_FNO) REFERENCES TBL_USER(USER_PNO) ON DELETE CASCADE
);
