DROP TABLE TBL_USERINFO;

CREATE TABLE TBL_USERINFO (
	USERINFO_USER_FNO NUMBER(10) UNIQUE NOT NULL,
	USERINFO_LANG VARCHAR(100),
	USERINFO_PHOTO VARCHAR(200),
	USERINFO_OTHER VARCHAR(500),
	USERINFO_PHONE VARCHAR(13) UNIQUE,
	CONSTRAINT USERINFO_USER_FNO FOREIGN KEY (USERINFO_USER_FNO) REFERENCES TBL_USER(USER_PNO) ON DELETE CASCADE
);

SELECT * FROM TBL_USERINFO;

COMMIT