DROP TABLE TBL_LIKE;

CREATE TABLE TBL_LIKE(
    LIKE_FEED_FNO NUMBER(10) NOT NULL ,
    LIKE_USER_FNO NUMBER(10) NOT NULL ,

    CONSTRAINT LIKE_FEED_FNO FOREIGN KEY (LIKE_FEED_FNO) REFERENCES TBL_FEED(FEED_PNO) ON DELETE CASCADE,
    CONSTRAINT LIKE_USER_FNO FOREIGN KEY (LIKE_USER_FNO) REFERENCES  TBL_USER(USER_PNO) ON DELETE CASCADE
);

INSERT INTO TBL_LIKE VALUES (1,1);

COMMIT